import type { GlossaryEntry } from "@/lib/types";

/**
 * Every technical term the 0606 syllabus expects a candidate to understand,
 * with the definition an examiner would accept. Terms that carry a mark when
 * used correctly in an explanation are the reason this page exists.
 */
export const GLOSSARY: GlossaryEntry[] = [
  { term: "Amplitude", definition: "Half the distance between the maximum and minimum of a sine or cosine curve. For $y = a\\sin bx + c$ it is $|a|$. A tangent curve has no amplitude.", topic: "trigonometric-functions" },
  { term: "Arc length", definition: "The distance along the curved edge of a sector: $s = r\\theta$, with $\\theta$ in radians.", topic: "circular-measure" },
  { term: "Arithmetic progression", definition: "A sequence in which each term is obtained by adding a fixed common difference $d$ to the previous term.", topic: "progressions" },
  { term: "Asymptote", definition: "A line the curve approaches arbitrarily closely but never reaches. $y = e^x$ has the horizontal asymptote $y=0$; $y = \\ln x$ has the vertical asymptote $x = 0$.", topic: "logarithms-exponentials" },
  { term: "Binomial coefficient", definition: "$\\binom{n}{r} = \\frac{n!}{r!(n-r)!}$, the number of ways of choosing $r$ objects from $n$, and the coefficient of $a^{n-r}b^r$ in $(a+b)^n$.", topic: "binomial-expansion" },
  { term: "Chord", definition: "A straight line joining two points on a curve. A line that meets a circle at two points is a chord of it.", topic: "circles" },
  { term: "Coefficient", definition: "The constant multiplying a term: in $5x^3$ the coefficient is 5.", topic: "quadratic-functions" },
  { term: "Collinear", definition: "Lying on one straight line. Three points are collinear when two displacement vectors between them are parallel and share a point.", topic: "vectors" },
  { term: "Combination", definition: "A selection in which order does not matter, counted by $^nC_r$.", topic: "permutations-combinations" },
  { term: "Common difference", definition: "The fixed amount added between consecutive terms of an arithmetic progression.", topic: "progressions" },
  { term: "Common ratio", definition: "The fixed multiplier between consecutive terms of a geometric progression. A sum to infinity exists only when $|r|<1$.", topic: "progressions" },
  { term: "Completing the square", definition: "Writing $ax^2+bx+c$ as $a(x+p)^2+q$, which reveals the vertex $(-p, q)$, the line of symmetry and the range.", topic: "quadratic-functions" },
  { term: "Composite function", definition: "$fg(x) = f(g(x))$ — apply $g$ first, then $f$. It exists only where the range of $g$ lies inside the domain of $f$.", topic: "functions" },
  { term: "Convergent", definition: "Of a geometric progression: having a finite sum to infinity, which happens exactly when $|r| < 1$.", topic: "progressions" },
  { term: "Cosecant", definition: "$\\operatorname{cosec}\\theta = \\dfrac{1}{\\sin\\theta}$. Undefined wherever $\\sin\\theta = 0$.", topic: "trigonometric-functions" },
  { term: "Cotangent", definition: "$\\cot\\theta = \\dfrac{\\cos\\theta}{\\sin\\theta} = \\dfrac{1}{\\tan\\theta}$.", topic: "trigonometric-functions" },
  { term: "Definite integral", definition: "$\\int_a^b f(x)\\,\\mathrm dx = F(b) - F(a)$: a number, not a family of functions, so no arbitrary constant appears.", topic: "integration" },
  { term: "Derivative", definition: "The gradient function $\\frac{\\mathrm dy}{\\mathrm dx}$, giving the gradient of the tangent at each point of a curve.", topic: "differentiation" },
  { term: "Discriminant", definition: "$b^2-4ac$. Positive means two distinct real roots, zero a repeated root, negative no real roots.", topic: "quadratic-functions" },
  { term: "Displacement", definition: "Position relative to a starting point, which may be negative. Distinct from distance travelled, which counts every metre regardless of direction.", topic: "kinematics" },
  { term: "Domain", definition: "The set of inputs a function accepts. It must exclude anything that makes the rule undefined — division by zero, roots of negatives, logs of non-positives.", topic: "functions" },
  { term: "Factor theorem", definition: "$(x-a)$ is a factor of $P(x)$ if and only if $P(a) = 0$.", topic: "factors-of-polynomials" },
  { term: "Geometric progression", definition: "A sequence in which each term is the previous one multiplied by a fixed common ratio $r$.", topic: "progressions" },
  { term: "Gradient", definition: "Rate of change of $y$ with respect to $x$; for a line, $\\frac{\\Delta y}{\\Delta x}$; for a curve, the derivative at a point.", topic: "straight-line-graphs" },
  { term: "Identity", definition: "An equation true for every value of the variable, such as $\\sin^2 A + \\cos^2 A = 1$. Proved by transforming one side into the other.", topic: "trigonometric-identities" },
  { term: "Indefinite integral", definition: "The family of antiderivatives of a function, always written with an arbitrary constant $+c$.", topic: "integration" },
  { term: "Inverse function", definition: "$f^{-1}$ undoes $f$. It exists only when $f$ is one–one, and its graph is the reflection of $y=f(x)$ in $y=x$.", topic: "functions" },
  { term: "Many–one function", definition: "A function where two or more inputs share an output, such as $x \\mapsto x^2$ on $\\mathbb{R}$. It has no inverse without a restricted domain.", topic: "functions" },
  { term: "Modulus", definition: "$|x|$, the distance of $x$ from zero, never negative. $y=|f(x)|$ reflects the parts of $y=f(x)$ below the $x$-axis upward.", topic: "equations-inequalities-graphs" },
  { term: "Normal", definition: "The line perpendicular to the tangent at a point on a curve; its gradient is $-\\frac1m$.", topic: "applications-of-differentiation" },
  { term: "One–one function", definition: "A function where different inputs always give different outputs; a horizontal line meets its graph at most once. Only these have inverses.", topic: "functions" },
  { term: "Period", definition: "The horizontal length of one complete cycle. For $\\sin bx$ and $\\cos bx$ it is $\\frac{2\\pi}{b}$; for $\\tan bx$ it is $\\frac{\\pi}{b}$.", topic: "trigonometric-functions" },
  { term: "Permutation", definition: "An arrangement in which order matters, counted by $^nP_r$.", topic: "permutations-combinations" },
  { term: "Position vector", definition: "The vector from the origin to a point. $\\overrightarrow{AB} = \\mathbf b - \\mathbf a$ is the displacement between two such points.", topic: "vectors" },
  { term: "Principal value", definition: "The single angle returned by $\\arcsin$, $\\arccos$ or $\\arctan$. Other solutions in an interval must be found from symmetry.", topic: "trigonometric-equations" },
  { term: "Radian", definition: "The angle subtended by an arc equal in length to the radius. $\\pi$ radians $= 180^\\circ$. All calculus with trigonometric functions assumes radians.", topic: "circular-measure" },
  { term: "Range", definition: "The set of outputs a function actually produces — its image set. Written in terms of $f(x)$ or $y$, never $x$.", topic: "functions" },
  { term: "Rationalise", definition: "To remove a surd from a denominator by multiplying top and bottom by the conjugate.", topic: "indices-and-surds" },
  { term: "Remainder theorem", definition: "Dividing $P(x)$ by $(x-a)$ leaves the remainder $P(a)$.", topic: "factors-of-polynomials" },
  { term: "Root", definition: "A value of $x$ that makes an expression zero — where its graph crosses or touches the $x$-axis.", topic: "quadratic-functions" },
  { term: "Secant", definition: "$\\sec\\theta = \\dfrac{1}{\\cos\\theta}$. Not to be confused with $\\cos^{-1}\\theta$, which is the inverse function.", topic: "trigonometric-functions" },
  { term: "Sector", definition: "The region of a circle between two radii and an arc. Its area is $\\frac12 r^2\\theta$ in radians.", topic: "circular-measure" },
  { term: "Segment", definition: "The region between a chord and its arc, with area $\\frac12 r^2(\\theta - \\sin\\theta)$.", topic: "circular-measure" },
  { term: "Stationary point", definition: "A point where $\\frac{\\mathrm dy}{\\mathrm dx} = 0$: a maximum or a minimum in this syllabus, since points of inflexion are excluded.", topic: "applications-of-differentiation" },
  { term: "Sum to infinity", definition: "$S_\\infty = \\frac{a}{1-r}$, defined only for a geometric progression with $|r| < 1$.", topic: "progressions" },
  { term: "Surd", definition: "An irrational root left in exact form, such as $3\\sqrt2$. Expected as the answer on the non-calculator paper.", topic: "indices-and-surds" },
  { term: "Tangent (to a curve)", definition: "The line touching a curve at a point, with the same gradient as the curve there. For a circle it is perpendicular to the radius at the point of contact.", topic: "applications-of-differentiation" },
  { term: "Turning point", definition: "A maximum or minimum of a curve, where the gradient changes sign.", topic: "applications-of-differentiation" },
  { term: "Unit vector", definition: "A vector of magnitude 1, found by dividing a vector by its own magnitude: $\\hat{\\mathbf a} = \\frac{\\mathbf a}{|\\mathbf a|}$.", topic: "vectors" },
  { term: "Vertex", definition: "The turning point of a parabola, at $(-p, q)$ when written as $a(x+p)^2+q$.", topic: "quadratic-functions" },
];
