#!/usr/bin/env python3
"""Bundle the ``evosim`` Python package into a single JS file for the browser.

The web viewer (``web/index.html``) runs the *real* EvoSim engine inside the
browser via Pyodide (CPython compiled to WebAssembly). Rather than fetch every
module at runtime, we serialize the package source into one JavaScript file:

    self.EVOSIM_FILES = { "evosim/simulation.py": "<source>", ... };

At startup ``app.js`` writes those files into Pyodide's virtual filesystem and
does ``import evosim`` -- so the browser executes the exact same headless engine
that drives the Pygame viewer and the headless runs. Nothing is re-implemented,
which keeps the science identical everywhere.

Only pure-Python/NumPy modules are needed; the Pygame and Matplotlib layers are
skipped because the browser front-end draws to an HTML canvas itself.

Usage::

    python -m scripts.build_web          # writes web/evosim_pkg.js
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "evosim"
OUT = ROOT / "web" / "evosim_pkg.js"

# Modules the browser build never imports (they pull in pygame / matplotlib).
# Excluding them keeps the bundle lean and free of unavailable dependencies.
EXCLUDE = {
    Path("evosim/render/pygame_renderer.py"),
    Path("evosim/render/blender_export.py"),
    Path("evosim/render/base.py"),
    Path("evosim/render/__init__.py"),
    Path("evosim/analysis/plots.py"),
    Path("evosim/analysis/__init__.py"),
}


def collect() -> dict[str, str]:
    files: dict[str, str] = {}
    for path in sorted(PKG.rglob("*.py")):
        rel = path.relative_to(ROOT)
        if "__pycache__" in rel.parts or rel in EXCLUDE:
            continue
        files[str(rel).replace("\\", "/")] = path.read_text(encoding="utf-8")
    return files


def main() -> None:
    files = collect()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(files, ensure_ascii=False, indent=0)
    banner = (
        "// AUTO-GENERATED by scripts/build_web.py -- do not edit by hand.\n"
        "// Regenerate after changing the evosim engine:  python -m scripts.build_web\n"
    )
    OUT.write_text(f"{banner}self.EVOSIM_FILES = {payload};\n", encoding="utf-8")
    total = sum(len(s) for s in files.values())
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(files)} modules, {total/1024:.1f} KB of source")


if __name__ == "__main__":
    main()
