"""Build the generated artefacts: one JSON index and the per-category tables.

    python scripts/build_index.py

Neither output is checked in. A generated file in a repository is a file that
goes stale the moment somebody edits the source and forgets to regenerate it,
and then there are two answers to the same question with nothing to say which
is current.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from aimodeldb.loader import load
from aimodeldb.render import markdown_table, to_json


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", default="data", type=Path)
    parser.add_argument("--json-out", default=Path("dist/database.json"), type=Path)
    parser.add_argument("--markdown-out", default=Path("docs/generated"), type=Path)
    args = parser.parse_args()

    database = load(args.data)

    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(json.dumps(to_json(database), indent=2, default=str) + "\n")
    print(f"wrote {args.json_out} ({len(database)} entries)")

    args.markdown_out.mkdir(parents=True, exist_ok=True)
    index = ["# Categories", "", "<!-- Generated by scripts/build_index.py. Do not edit. -->", ""]
    for category in database.taxonomy.categories:
        entries = database.by_category(category.id)
        index.append(f"- [{category.label}]({category.id}.md) — {len(entries)} entries")
        page = [
            f"# {category.label}",
            "",
            f"**{category.question}**",
            "",
            category.definition.strip(),
            "",
            "Tiers are groupings, not a ranking. Entries within a tier are alphabetical.",
            "",
            markdown_table(database, category.id),
            "",
            "Every row links to the entry's primary official source. Check the "
            "`last_verified` date in `data/entries/` before relying on a price.",
            "",
        ]
        (args.markdown_out / f"{category.id}.md").write_text("\n".join(page))

    (args.markdown_out / "index.md").write_text("\n".join([*index, ""]))
    print(f"wrote {len(database.taxonomy.categories) + 1} markdown files to {args.markdown_out}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
